### ISSUE TITLE
tech stack lack of

### ISSUE THREAD

**Issue by dogukanergezer** [ozivarol/Bff-sTalks#1]
The readme file is not illustrative enough. What language was the UI screen written in?

**Comment by ozivarol** [comment]
I can edit my friend

Doğukan Ergezer ***@***.***>, 12 Eki 2021 Sal, 18:50
tarihinde şunu yazdı:

**Comment by dogukanergezer** [comment]
I'm waiting my friend

**Comment by dogukanergezer** [comment]
thanks a lot dude
